name: "toxicity_classifier"
backend: "python"

max_batch_size: 8

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "TOXICITY_LOGITS"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]